[project]
name = "ccx-data-pipeline"
version = "0.0.0"
requires-python = ">=3.11"
dependencies = [
    "insights-core>=3.6.11",
    "ccx-ocp-core",
    "ccx-messaging==4.3.5",
    "ccx-rules-ocp==2026.01.27",
]
